# permissions for end users to view ghosts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ghost-viewer-role
rules:
- apiGroups:
  - apps.exnet.systems
  resources:
  - ghosts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.exnet.systems
  resources:
  - ghosts/status
  verbs:
  - get
