# permissions for end users to edit ghosts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ghost-editor-role
rules:
- apiGroups:
  - apps.exnet.systems
  resources:
  - ghosts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.exnet.systems
  resources:
  - ghosts/status
  verbs:
  - get
