---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
  ##
  ## Base operator rules
  ##
  - apiGroups:
      - ""
      - extensions
    resources:
      - secrets
      - services
      - pods
      - pods/exec
      - pods/log
      - persistentvolumeclaims
      - networking.k8s.io
    verbs:
      - "*"
  - apiGroups:
      - apps
    resources:
      - deployments
      - daemonsets
      - replicasets
      - statefulsets
      - ingresses
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  ##
  ## Rules for apps.exnet.systems/v1alpha1, Kind: Ghost
  ##
  - apiGroups:
      - apps.exnet.systems
    resources:
      - ghosts
      - ghosts/status
      - ghosts/finalizers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
      #fatal: [localhost]: FAILED! => {"changed": false, "error": 403, "msg": "Failed to retrieve requested object: b'{\"kind\":\"Status\",\"apiVersion\":\"v1\",\"metadata\":{},\"status\":\"Failure\",\"message\":\"ingresses.extensions \\\\\"ghost-test-ingress\\\\\" is forbidden: User \\\\\"system:serviceaccount:ghost-system:default\\\\\" cannot get resource \\\\\"ingresses\\\\\" in API group \\\\\"extensions\\\\\" in the namespace \\\\\"default\\\\\"\",\"reason\":\"Forbidden\",\"details\":{\"name\":\"ghost-test-ingress\",\"group\":\"extensions\",\"kind\":\"ingresses\"},\"code\":403}\\n'", "reason": "Forbidden", "status": 403}
      #fatal: [localhost]: FAILED! => {"changed": false, "error": 403, "msg": "Failed to retrieve requested object: b'{\"kind\":\"Status\",\"apiVersion\":\"v1\",\"metadata\":{},\"status\":\"Failure\",\"message\":\"ingresses.extensions \\\\\"ghost-test-ingress\\\\\" is forbidden: User \\\\\"system:serviceaccount:ghost-system:default\\\\\" cannot get resource \\\\\"ingresses\\\\\" in API group \\\\\"extensions\\\\\" in the namespace \\\\\"default\\\\\"\",\"reason\":\"Forbidden\",\"details\":{\"name\":\"ghost-test-ingress\",\"group\":\"extensions\",\"kind\":\"ingresses\"},\"code\":403}\\n'", "reason": "Forbidden", "status": 403}
# +kubebuilder:scaffold:rules
#E1222 13:31:11.644961       7 reflector.go:127] pkg/mod/k8s.io/client-go@v0.19.4/tools/cache/reflector.go:156: Failed to watch extensions/v1beta1, Kind=Ingress: failed to list extensions/v1beta1, Kind=Ingress: ingresses.extensions is forbidden: User "system:serviceaccount:ghost-system:default" cannot list resource "ingresses" in API group "extensions" at the cluster scope
#fatal: [localhost]: FAILED! => {"changed": false, "error": 422, "msg": "Failed to create object: b'{\"kind\":\"Status\",\"apiVersion\":\"v1\",\"metadata\":{},\"status\":\"Failure\",\"message\":\"Deployment.apps \\\\\"ghost-test-ghost\\\\\" is invalid: [spec.template.spec.containers[0].volumeMounts[0].name: Not found: \\\\\"ghost-test-data-pvc\\\\\", spec.template.spec.containers[0].volumeMounts[1].name: Not found: \\\\\"tmp-dir\\\\\"]\",\"reason\":\"Invalid\",\"details\":{\"name\":\"ghost-test-ghost\",\"group\":\"apps\",\"kind\":\"Deployment\",\"causes\":[{\"reason\":\"FieldValueNotFound\",\"message\":\"Not found: \\\\\"ghost-test-data-pvc\\\\\"\",\"field\":\"spec.template.spec.containers[0].volumeMounts[0].name\"},{\"reason\":\"FieldValueNotFound\",\"message\":\"Not found: \\\\\"tmp-dir\\\\\"\",\"field\":\"spec.template.spec.containers[0].volumeMounts[1].name\"}]},\"code\":422}\\n'", "reason": "Unprocessable Entity", "status": 422}