---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
  ##
  ## Base operator rules
  ##
  - apiGroups:
      - ""
      - extensions
      - networking.k8s.io
    resources:
      - secrets
      - services
      - pods
      - pods/exec
      - pods/log
      - persistentvolumeclaims
      - ingresses
    verbs:
      - "*"
  - apiGroups:
      - apps
    resources:
      - deployments
      - daemonsets
      - replicasets
      - statefulsets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  ##
  ## Rules for apps.exnet.systems/v1alpha1, Kind: Ghost
  ##
  - apiGroups:
      - apps.exnet.systems
    resources:
      - ghosts
      - ghosts/status
      - ghosts/finalizers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
E0112 10:06:00.410573       7 reflector.go:127] pkg/mod/k8s.io/client-go@v0.19.4/tools/cache/reflector.go:156: Failed to watch networking.k8s.io/v1, Kind=Ingress: failed to list networking.k8s.io/v1, Kind=Ingress: ingresses.networking.k8s.io is forbidden: User "system:serviceaccount:ghost-system:default" cannot list resource "ingresses" in API group "networking.k8s.io" at the cluster scope
E0112 10:07:19.998385       7 reflector.go:127] pkg/mod/k8s.io/client-go@v0.19.4/tools/cache/reflector.go:156: Failed to watch networking.k8s.io/v1, Kind=Ingress: failed to list networking.k8s.io/v1, Kind=Ingress: ingresses.networking.k8s.io is forbidden: User "system:serviceaccount:ghost-system:default" cannot list resource "ingresses" in API group "networking.k8s.io" at the cluster scope