---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
  ##
  ## Base operator rules
  ##
  - apiGroups:
      - ""
      - extensions
    resources:
      - secrets
      - services
      - pods
      - pods/exec
      - pods/log
      - persistentvolumeclaims
      - networking.k8s.io
    verbs:
      - "*"
  - apiGroups:
      - apps
    resources:
      - deployments
      - daemonsets
      - replicasets
      - statefulsets
      - ingresses
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  ##
  ## Rules for apps.exnet.systems/v1alpha1, Kind: Ghost
  ##
  - apiGroups:
      - apps.exnet.systems
    resources:
      - ghosts
      - ghosts/status
      - ghosts/finalizers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
